version: "3.8" # Specify Compose file version

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5234:5234"
    env_file:
      - .env
    container_name: instagram_analyzer_dev
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
